# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *

class Ui_MainWindow_history(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(350, 60, 301, 51))
        self.label_title.setObjectName("label_title")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(290, 200, 721, 471))
        self.tableWidget.setStyleSheet(
            "background-color: #FFF0F5;"
            "selection-color: yellow;"
            "selection-background-color: blue;"
            "border:2px groove gray;border-radius:10px;padding:2px 4px"
        )
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(290, 150, 131, 31))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 131, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 270, 191, 31))
        self.lineEdit.setStyleSheet(
            "background-color: #FFF0F5;"
            "selection-color: yellow;"
            "selection-background-color: blue;"
            "border:2px groove gray;border-radius:10px;padding:2px 4px"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 330, 131, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 380, 191, 31))
        self.lineEdit_2.setStyleSheet(
            "background-color: #FFF0F5;"
            "selection-color: yellow;"
            "selection-background-color: blue;"
            "border:2px groove gray;border-radius:10px;padding:2px 4px"
        )
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.pushButton_qurey = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_qurey.setGeometry(QtCore.QRect(60, 450, 191, 41))
        self.pushButton_qurey.setStyleSheet(
            "QPushButton{color:#F0FFFF}"  # 按键前景色
            "QPushButton{background-color:#7EC0EE}"  # 按键背景色
            # "QPushButton:hover{color:red}"  # 光标移动到上面后的前景色
            "QPushButton{font:bold 18px}"
            "QPushButton{border-radius:6px}"  # 圆角半径
            "QPushButton:pressed{background-color:rgb(180,180,180);border: None;}"  # 按下时的样式
        )
        self.pushButton_qurey.setObjectName("pushButton_qurey")

        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(60, 520, 191, 41))
        self.pushButton_clear.setStyleSheet(
            "QPushButton{color:#F0FFFF}"  # 按键前景色
            "QPushButton{background-color:#7EC0EE}"  # 按键背景色
            # "QPushButton:hover{color:red}"  # 光标移动到上面后的前景色
            "QPushButton{font:bold 18px}"
            "QPushButton{border-radius:6px}"  # 圆角半径
            "QPushButton:pressed{background-color:rgb(180,180,180);border: None;}"  # 按下时的样式
        )
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(60, 580, 191, 41))
        self.pushButton_exit.setStyleSheet(
            "QPushButton{color:#F0FFFF}"  # 按键前景色
            "QPushButton{background-color:#7EC0EE}"  # 按键背景色
            # "QPushButton:hover{color:red}"  # 光标移动到上面后的前景色
            "QPushButton{font:bold 18px}"
            "QPushButton{border-radius:6px}"  # 圆角半径
            "QPushButton:pressed{background-color:rgb(180,180,180);border: None;}"  # 按下时的样式
        )
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def paintEvent(self, a0: QtGui.QPaintEvent) -> None:
        painter = QPainter(self)
        pixmap = QPixmap("img/background/bkg.jpg")
        painter.drawPixmap(self.rect(), pixmap)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "高铁异物检测系统"))
        MainWindow.setWindowIcon(QIcon("title.ico"))
        self.label_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;color:#363636;\">图片识别记录</span></p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;color:#363636;\">识别历史</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;color:#363636;\">按日期查询:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;color:#363636;\">按名称查询:</span></p></body></html>"))
        self.pushButton_qurey.setText(_translate("MainWindow", "查询"))
        self.pushButton_clear.setText(_translate("MainWindow", "清除所有记录"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出"))
